### PR TITLE
Using `joinpath` for constructing path variables

### PR DESCRIPTION
**Pull request by arosen93**
This is to address #72 regarding the use of `joinpath` to enable Windows-compatibility with filepaths (and to have a more robust method of constructing filepaths without worrying about slashes). I think I got them all. I have run the test suite, and everything passed on my Windows machine. Let me know if there's any issues, and I'll gladly take care of it.

### CODE REVIEW

**Comment by ahyork** [comment]
Thanks for this fix @ @arosen93 ! I just resolved a conflict in src/PorousMaterials because I had added some functions relating to the path recently. Once the travis-ci tests run everything should be good to merge this in!

**Comment by SimonEnsemble** [comment]
@arosen93 yes, thank you for contributing to `PorousMaterials.jl`! I am adding some more functionality to the grids right now: checking whether a given point in the grid is accessible through a channel.

**Comment by arosen93** [comment]
@SimonEnsemble Of course! And that's awesome. I was a bit behind schedule and hadn't had a chance to check out the grids yet. Going to do that later today. I'll reach out if there are any issues!

**Comment by ahyork** [comment]
@arosen93 All the tests pass except for the path_test.jl suite. This was added after you cloned the repo but before this pr, I tried to push a commit to fix this but I didn't have access. Could you update your fork to match our master branch and then fix the three `@test`s in test/path_test.jl?

**Comment by ahyork** [comment]
The `set_path_to_data(pwd())` and `set_path_to_data()` are function calls changing the `PATH_TO_DATA` variable, and shouldn't be inside of the `joinpath` calls. Sorry I haven't commented these tests

**Comment by arosen93** [comment]
@ahyork Oops! Just assumed there was a `*` operator there. I think I got it now... maybe! Let's try again.

**Comment by ahyork** [comment]
@arosen93  I think this should do it! Thank you again for helping us switch everything over to `joinpath`!

**Comment by arosen93** [comment]
Great! Glad to help out!

**Comment by ahyork** [comment]
@arosen93 Almost there! One of the three tests failed:

`Expression: PorousMaterials.PATH_TO_DATA == joinpath(dirname(pathof(PorousMaterials)), "../test/data/")
   Evaluated: "/home/travis/build/SimonEnsemble/PorousMaterials.jl/src/../test/data" == "/home/travis/build/SimonEnsemble/PorousMaterials.jl/src/../test/data/"`

I think to fix this we need to split the `joinpath(dirname(pathof(PorousMaterials)),"../test/data/")` into `joinpath(dirname(pathof(PorousMaterials)), "..", "test", "data")`

**Comment by arosen93** [comment]
@ahyork Sounds reasonable. I wasn't sure if that one would work. I think that works in Python, so I was hoping it'd work here. Let's hope this one fixes it! Nearly there.

**Pull request merged**
