### PR TITLE
Symmetry reader

### PR DESCRIPTION
**Pull request by ahyork**
Allow PorousMaterials to read in *.cif files that are not in P1 symmetry. This allows any cif file to be read in as long as it has symmetry operations.

### CODE REVIEW

**Comment by ahyork** [comment]
going to add framework addition with this pull request as well

**Comment by Surluson** [comment]
Great job! There are a few things I noticed going over this. I believe the symmetry operations need a bit more work, as it fails on some `.cif` files I tried it on.

I'll split this up based on the files you modified/created:
**Crystal.jl**:
- See [this](https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Ispace_group_name_H-M_alt.html) for the "_space_group_name_H-M_alt" tag. It seems this tag is not consistent as it is arbitrarily chosen by the user (and the website recommends not having a computer read this). Were there any cases you saw where they would report the space group with that tag instead of the normal "_symmetry_space_group_name_H-M"?
- In lines 167-174 there's a for-loop checking the symmetry operations with if-statements. I'm not super familiar with these operations, but I've seen operations like `-x+y,-x,z`. Wouldn't the if-statements fail in this case, by putting the first two expressions in `new_sym_rule[1]`? I'm getting `UndefVarError: y not defined`, which I believe is connected to this problem.
- Leftover commented line on line 226
- Is the elementwise assignment necessary on line 232? Wouldn't `coords = mod.(coords, 1.0)` give the same result?

- Some `.cif` files contain more loops than atom_site and symmetry_equiv. Unfortunately, some of them contain `atom_site` like `_geom_bond_atom_site_label_1`. When this happens, the while loops tries to use the key `_atom_site_fract_x` or something equivalent, and fails because `name_to_column` is re-initialized, resulting in a KeyError. An example of this is `ORIVOC.cif` which I've attached below.

**Matter.jl**:
- I'm not well versed in `issetequal`. What's the advantage of using that method in `isapprox(a1::Atoms, a2::Atoms)` over what was implemented before?

**crystal_test.jl**:
- Typo on line 38
- Back to the point I made in *Crystal.jl*. KAXQIL is a really nice MOF in that the P1 symmetry operations don't have x, y or z in the same call (no operations like `-x+y,-x,z`), so I'm not sure this is the best example to test the change to P1 symmetry. An example of a MOF more difficult to deal with is Zn-MOF-74 (Refcode: ORIVOC). I've uploaded a .txt file of ORIVOC (Github doesn't allow me to attach a `.cif` file) as a reference.
[ORIVOC.txt](https://github.com/SimonEnsemble/PorousMaterials.jl/files/3433487/ORIVOC.txt)

I have no further comments on the other files that were modified/created

-Árni

**Comment by ahyork** [comment]
Good catch on the symmetry rules! I will try and find a fix for that. 

I changed the `isapprox` to `issetequal` in `Matter.jl` because the set comparison won't be based on position within the array. I was getting issues where I would convert a framework to P1 symmetry in PorousMaterials and with OpenBabel and they would be considered different frameworks because the order of atoms was different. 

I will combine the positions and the species to maintain that the same atom type is at the same position, the current method won't catch this.

**Comment by ahyork** [comment]
I am getting the 'space_group_name_H-M_alt' when I convert files to P1 using OpenBabel 2.4.1.

It looks like there aren't extended symbols/alternate forms for P1 symmetry. Would we be able to leave H-M_alt in because we would ignore all of the extended forms of non-P1 symmetry?

**Comment by ahyork** [comment]
I think I have addressed all of the issues you found with the code in the first review. Here are a few that I was unsure of:

**Crystal.jl**
- `_space_group_name_H-M_alt` doesn't have alternate tags for P1 symmetry, and since we are only interested in whether it is in P1 would this work? I looked at International Tables for Crystallography Vol. A (2002) table 4.3.2.1 and it showed the possible names for spacegroups and P1 is always the same.
- I adjusted the symmetry operations so that the anonymous functions take in an (x,y,z) so that it can understand operations like `x+y`
- I fixed the `_atom_site` checker to only compare to the beginning of the string, and I have expanded it to take in Cartesian coordinates as well. Would it be better to add a flag so that after it reads in coordinates the first time it will ignore `_atom_site` for the rest of the file?

**Matter.jl**
- I talked about this a little bit above, but using `issetequal` will allow the coordinates to be in a different order and still be the same. i.e.
- `isapprox([1, 2, 3], [3, 2, 1])` is false
- `issetequal(Set([1, 2, 3]), Set([3, 2, 1]))` is true

**crystal_test.jl**
- I changed the test to read in `ORIVOC.cif`
- I test frameworks by cleaning ORIVOC.cif in Avogadro and converting it to P1 using OpenBabel (this is the baseline).
- I compare this to `ORIVOC_clean.cif` which is the direct output of cleaning it in Avogadro. This is in Cartesian coordinates
- I also compare to `ORIVOC_clean_fract.cif` which is `ORIVOC_clean.cif` after being sent through OpenBabel to get the coordinates in fractional (this felt redundant, why allow PorousMaterials to read in any symmetry if you still need to send it through OpenBabel, and this is why I added the Cartesian reader)

This is where I am at for reading in symmetry, let me know what you think!

Thanks,
Arthur

**Comment by Surluson** [comment]
**Crystal.jl**:

- Yeah I agree with you on the `_space_group_name_H-M_alt` tag. I thought it was an alternative tag to the `_space_group_name_H-M` tag, but it seems the latter is being discontinued for some reason (?)
- I like the symmetry operations :+1: 
- I'm still a bit skeptical on the `_atom_site` part. I think whoever's making the `.cif` file can choose to have an `_atom_site_label` at the start of any `_loop`, not necessarily the coordinate loop. Maybe the best way to do this is just to read everything in all the loops and store it in dictionaries, and later find the key that corresponds to the coordinate loop? Maybe just explicitly look for the `_atom_site_fract_` keywords? I'm not entirely sure how to solve this problem. Line 148 threw me an error because the function tried to read another `_loop` that started with `_atom_site_aniso_label` (I think) when I tried reading in another `.cif` file.

**Matter.jl**:

- Thanks for the clarification, that makes a lot more sense :+1: 

**crystal_test.jl**:

- Maybe we should look for a test case where there isn't any overlap. What do you think? It doesn't look like there's overlap in the original symmetry, so I'm confused as to why there's overlap in P1 symmetry. It could be that the symmetry operations in the `.cif` files are wrong (?) I'm getting overlap in both PorousMaterials and openbabel, so I don't think it's necessarily an issue on our part.

**Comment by ahyork** [comment]
I like your idea for checking for coordinates. I think I will change it to always read the dictionary, then check to see if it contains `_atom_site_fract_` or `_atom_site_Cartn_`.

I'm also not sure what is going on with the overlap in "ORIVOC.cif". I opened a P1 and a non-P1 version side-by-side and couldn't find any differences, so I'm guessing it would be something with the symmetry operations. Should I add back the tests with SBMOF-1 in non-P1 symmetry or would there be more rigorous MOFS we could test against?

In the commit I just made I added a flag to frameworks for storing whether they are in P1 symmetry. It will be important to know whether it is in P1 before running simulations, and adding a boolean member is faster than running a long check. I put assertions in the gcmc simulations and the henry coefficient simulations. Are there any other places where we should assert P1 symmetry?

**Comment by ahyork** [comment]
Will there be other issues with the `_symmetry_equiv_pos_as_xyz` flag we look for? Or can that stay the same?

**Comment by Surluson** [comment]
I haven't seen anything that `_symmetry_equiv_pos_as_xyz` might raise an issue with, so I think that's fine.

Right now, I don't see any extra spots to assert P1 symmetry. (I might get back to that later though)

**Comment by ahyork** [comment]
Half of the builds for the last commit failed because they didn't have a good connection and couldn't grab our files. The builds that could download our code passed.

**Comment by ahyork** [comment]
I replaced the ORIVOC testing files with structure number 4 found [here](https://pubs.acs.org/doi/abs/10.1021/ja205976v). It looks like the issue was specific to the cif file because this structure has the same space group as ORIVOC but it doesn't have overlapping atoms.

Another interesting thing is that when I read in ORIVOC with `f = Framework("ORIVOC_clean"; check_atom_and_charge_overlap=true)` and wrote that file out the structure had three 'rings' and one of them was outside the unit cell.

**Comment by SimonEnsemble** [comment]
we need a `assert_P1_symmetry(framework)` in `Grids.jl` where we write the energy grids too. in `energy_grid()`

**Comment by ahyork** [comment]
This should be good to go now. I have finished everything I wanted with the `symmetry_reader` and `framework_bonds` branches. I merged the `framework_bonds` branch into this because I ended up building off of what I had already done in `symmetry_reader`. 

I also added julia 1.2 to the testing file. 

Let me know if there are any other features I should add or if there are any other test I should include.

**Comment by ahyork** [comment]
removed julia 1.2 testing because it was getting a timeout issue with travis during the electrostatic_energetics test. I looked into some ways to fix it but I will do that in a separate branch and pr.

**Comment by Surluson** [comment]
*Crystal.jl*

* Will rephrase a few docstrings

* change order of if-statements. When using `&&`, if the first boolean is false, it won't even look at the next booleans. So in the case of an if-statement like the following:
```
 elseif haskey(name_to_column, "_geom_bond_atom_site_label_1") &&                                               
          (name_to_column, "_geom_bond_atom_site_label_2") &&
          read_bonds_from_file
```
switching it to 
```
 elseif read_bonds_from_file && 
          haskey(name_to_column, "_geom_bond_atom_site_label_1") &&                                               
          (name_to_column, "_geom_bond_atom_site_label_2")
```
will make it so that `haskey` will not be called if `read_bonds_from_file = false`

* __`space_group = reduce((x, y) -> x * " " * y, line[2:end])` is a nice solution to joining the strings if there's a whitespace in the space group string. But wouldn't string(line[2:end]...) do the same thing? I'll leave it as is right now because there might be something more happening that's not obvious to me.__

* Changing the following
```
for (name, column) in name_to_column
    if column == 1
        atom_column_name = name
    end
end
```
to `atom_column_name = [name for (name, column) in name_to_column if column == 1][end]`. Same thing, different syntax. __This doesn't take into consideration if more than one key has the same value (which the old code didn't either), but I'm not sure if that would even be possible. Thoughts?__

*__Is it necessary to have `strip_numbers_from_atom_labels!(framework)` in the construction of `Framework`? Right now I don't see a case to not include it, but we might be throwing information away.__

*`wrap_to_unit_cell` is checked twice. Will remove one check

I'll make the changes I mentioned but all discussion is welcome, especially regarding the bolded points.

**Comment by ahyork** [comment]
Do we want to add the default bonding rule function to the docs page? You can add it under docs/src/manual and then under whichever file you think is most appropriate. Add the function name to one of the ```@docs sections and it will render the docstrings when you build the site

**Comment by Surluson** [comment]
Good point. Will add it :+1:

**Comment by SimonEnsemble** [comment]
@Surluson @ahyork 

```
# Base.isapprox(a1::Atoms, a2::Atoms) = (a1.species == a2.species) && isapprox(a1.xf, a2.xf)
Base.isapprox(a1::Atoms, a2::Atoms; atol::Float64=1e-6) = issetequal(
    Set([(round.(a1.xf[:, i], digits=Int(abs(log10(atol)))), a1.species[i]) for i in 1:a1.n_atoms]),
    Set([(round.(a2.xf[:, i], digits=Int(abs(log10(atol)))), a2.species[i]) for i in 1:a2.n_atoms])) 
```
where is this needed? I think it should be the commented out line because e.g. `x=[1, 2]` should not be equal to `y=[2,1]`. this could lead to dangerous behavior if we wanted to always assume that for example the second atom was an oxygen in two frameworks. we could have a separate function for whether or not they are equal sets. is there some application where the atoms get all jumbled up?

**Comment by Surluson** [comment]
the old `isapprox` methods have been moved to new functions:

* `has_same_set_of_atoms` for `Atoms`
* `has_same_set_of_charges` for `Charges`
* `has_same_sets_of_atoms_and_charges` for `Framework`s

**Comment by SimonEnsemble** [comment]
@Surluson @ahyork careful [here, old line 441 of Crystals.jl](https://github.com/SimonEnsemble/PorousMaterials.jl/pull/114/commits/a22a047bef7eb2c0c8f25e05ef13fae43c6e1200): the replicated framework was being returned before undergoing overlap checks and having atoms being wrapped to [0, 1]. I think that the adsorption simulations would be incorrect if the atoms aren't wrapped to [0, 1] and we wouldn't have known when there were (erroneously) overlapping atoms from applying the symmetry operations.

**Comment by SimonEnsemble** [comment]
@ahyork @Surluson thanks for your work on this PR, it's great to have these two new features! Finally merged :)

**Pull request merged**
