### PR TITLE
Eos 2

### PR DESCRIPTION
**Pull request by silsbyc96**
Each test ran separately and passed. Must wait to confirm build is successful

### CODE REVIEW

**Comment by SimonEnsemble** [comment]
@ahyork do you know how we can only see the commits that differ from master when pull requests are made?
Is it `git rebase master`?

**Comment by ahyork** [comment]
`git rebase master` is basically a cleaner way of doing a merge. It takes the current state of master then stacks all of the commits from the branch on top of it. It would still show all of the commits, but the changes would be based off the current state of master I believe.

**Comment by ahyork** [comment]
Before we merge this we should get rid of all the `.DS_Store` files. I have issues with them and `.AppleDouble` files because they aren't readable and cause errors when they are in folders with my data.

Do we want all of the `*.jld2` files in this repo? we might want to remove them as well.

**Comment by SimonEnsemble** [comment]
@ahyork agreed, plz don't merge this until we can see the commits and how they differ from master.
@silsbyc96 can you `git rebase master`?
`git add *` is dangerous as it adds all files to the github repo, of which many probably don't belong in the repo. you can remove e.g. jld files via `git rm -f *.jld`

**Comment by SimonEnsemble** [comment]
pull request is stale.

looks like `git rebase master` would have better than `git merge master` since there are too many changes listed here to review.

see [here](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request).

**Pull request closed without merging**
