### PR TITLE
Framework separation

### PR DESCRIPTION
**Pull request by ahyork**
- framework_partition allows the user to create partitions of frameworks
- subtract_atoms allows the user to remove a set of atoms from a framework
- updated framework addition to correctly add the bonds

### CODE REVIEW

**Comment by SimonEnsemble** [comment]
@ahyork there is a conflict with the `crystal_test.jl` from your last PR? I'm not sure what happened; in the last PR it looked like the entire file was changed owing to e.g. tabs/spacing?

**Comment by ahyork** [comment]
The last PR had issues because I used `dos2unix` to remove some annoying windows line endings and it modified the entire file. I can download the old one and do a `vim -D` with the two files to show the differences

**Comment by ahyork** [comment]
after_resolve
before_resolve

**Comment by ahyork** [comment]
This is the output from `vim -d` when I opened the conflicted files side by side. The file on the left is the master branch and the file on the right is the new branch.

**Pull request merged**
