### PR TITLE
Documentation Website

### PR DESCRIPTION
**Pull request by ahyork**
Here is the current state of the documentation website. @CorySimon we will need to add some things to your Travis-CI account so that it automatically updates and writes the changes every time a pull request to master is approved. 

We should wait until everyone has gone through and double checked their docstrings as well as what I wrote for the about.md files. If you want to see what your docstrings will look you can run the make.jl file in the docsc folder, and check what the .md files in build look like. 

DO NOT commit anything inside of the build/ or site/ directories, these will be in the gh-pages branch written by Travis-CI.

If you want to see the entire site, you can use mkdocs to run it locally. Use mkdocs build then mkdocs serve and it will give you an address to find the site.

I do not have my notes with me at the moment, I will post a list of the functions I wrote docstrings for, so people can know specific ones to check.

### CODE REVIEW

**Comment by ahyork** [comment]
Here is a list of the functions and structs I wrote headers for based on the files they come from.

Energetics_Util.jl
PotentialEnergy
SystemPotentialEnergy

GCMC.jl
gcmc_result_savename

Henry.jl
henry_result_savename

MChelpers.jl
rotatable

Molecules.jl
charged

I was writing these headers so I would have some documentation show up when I ran the site locally. Everyone should take a look and make sure all functions are accurate and descriptive.

**Comment by Surluson** [comment]
Give me a bit before we merge. I'll be reviewing most of the docstrings again (Will update my changes here)

**Comment by ahyork** [comment]
Ok, I was working through the issues you found, and found a few more in ElectrostaticsEnergetics.jl. I'll commit and push in a few minutes

**Comment by ahyork** [comment]
I am going to work on the PATH functions now so those will have documentation when the site goes up.

**Comment by Surluson** [comment]
I made some extra edits. There is still some minor stuff to finish in `ElectrostaticEnergetics.jl`.
A lot of the changes were adding `Returns`/`Arguments`/`Attributes`.
Others were changing old `LJSpheres`/`PtCharges` to the new `Atoms`/`Charges` in the docstrings

**Comment by SimonEnsemble** [comment]
@Surluson let us know after you've run through the tutorials on the main documentation pages too, to make sure they run, help improve.
@ahyork I suppose I'll try to merge this when you're around so we can trouble shoot in case the website doesn't display? does this include a documentation badge on the README?

**Comment by ahyork** [comment]
I haven't put a documentation badge in the README, I can work on that and remove everything else from the README since it will be in the docs. When would be a good time for you to meet up and merge this?

**Pull request merged**
