### PR TITLE
refactored grid functions to take grid_dx input instead of n_pts

### PR DESCRIPTION
**Pull request by eahenle**
@SimonEnsemble this will be a breaking-change for existing energy-grid and accessibility scripts.  could refactor to allow `n_pts` arg as alternative to `grid_dx` to allow backward compatibility

### CODE REVIEW

**Comment by SimonEnsemble** [comment]
I think we shld keep `n_pts` as an argument, e.g. for ML we might want fixed-size grids. I was thinking just to make the `required_n_pts` exposed and put that in the grids documentation. then the user has to call that if they want a certain `dx`.

oh another elegant option is to axe `n_pts` and change it to:
`resolution::Union{Float64, Tuple{Int, Int, Int}}`. if `isa(resolution, Float64)` `dx=resolution` then computes `n_pts` from `dx`. if `isa(resolution, Tuple{Int, Int, Int})` `n_pts=resolution` and proceed.

**Comment by eahenle** [comment]
`required_n_pts` actually was already exposed and documented.  Implementing `resolution` as suggested.

**Comment by eahenle** [comment]
@SimonEnsemble ready to merge

**Comment by SimonEnsemble** [comment]
CC @ngantzler the `energy_grid` function now takes in an argument `resolution` instead of `n_pts`. can be Float to specify resolution or a tuple to specify number of points

**Pull request merged**
