### PR TITLE
Revised EOS

### PR DESCRIPTION
**Pull request by huynmela**
Revised EOS script to include VdW EOS along with modified VdW properties csv. Changed gas to fluid and modified docs to include VdW.

### CODE REVIEW

**Comment by ahyork** [comment]
This had errors when running with julia 0.7 on [travis build 426](https://travis-ci.org/SimonEnsemble/PorousMaterials.jl/jobs/557518955) that were not present in julia 1.0. I dropped support for julia 0.7 with this branch and added testing for julia 1.1

**Comment by SimonEnsemble** [comment]
@huynmela looks great. Before merging, please:

* remove "***NOTE: Do not delete the last three comment lines..." from the doc strings. 
* Please allow CSV to read in the `.csv` files and skip the lines marked as a comment `#`. See [here](https://juliadata.github.io/CSV.jl/stable/#Commented-Rows-1) for how to do so.
* Please put the source of where you got the PengRobinson and VdW params *inside the .csv* files. It is better here as opposed to the documentation because we should let the user amend these with their own comments and with params from different sources (negating the docs).
* ask @ahyork  for help with this: to ensure that CSV is up to date to allow reading in comments; I believe this is a recent development.

**Comment by SimonEnsemble** [comment]
when you put `CSV 0.5.9` in the `REQUIRE` file, does that mean CSV.jl has to be 0.5.9 version, or >0.5.9 is okay?

**Comment by ahyork** [comment]
Having `CSV 0.5.9` sets a floor for CSV at version 0.5.9, so anything >0.5.9 will also work

**Pull request merged**
