### PR TITLE
Flexible file paths

### PR DESCRIPTION
**Pull request by SimonEnsemble**
this PR allows users to use arbitrary paths for crystal structure, force field, molecule, and grid files.

we now hv a e.g. `PATH_TO_CRYSTALS` global variable for crystals. this allows users to place xtal structure files in any folder they want!

note we don't need separate functions to change these. i noted in the docs that we can do:
```
@eval PorousMaterials PATH_TO_CRYSTALS = pwd()
```
to change these variables directly.

this PR will give users more flexibility in how they want to store files.

@wisehe this PR will allow you to read `.cif`s from whatever folder you want.

### CODE REVIEW

**Comment by SimonEnsemble** [comment]
@ahyork thank you for thoroughly reviewing my PR and making additional tests. Woops, you are right. Could you please fix that then? I agree that it should be `joinpath(PATH_TO_MOLECULES, species)` not `joinpath(PATH_TO_DATA, PATH_TO_MOLECULES, species)` since `PATH_TO_MOLECULES` defaults to having `PATH_TO_DATA` in the first x entries.

**Comment by ahyork** [comment]
Sure thing! We don't have an `isapprox(forcefield1, forcefield2)` so there isn't a test for it, but it will throw an error if it is unable to use the new path and fail the build.

**Comment by SimonEnsemble** [comment]
@ahyork very odd: the path tests fail on travis but run fine on my local machine. do you know why?

**Comment by SimonEnsemble** [comment]
if u don't run `grid_tests.jl` first, then there is no grid for `path_grid.jl`... this might be the issue...

**Comment by SimonEnsemble** [comment]
this is the culprit! the grid's origin was random! so if we push this grid file to `other_grid` then it will differ from in `data/grids` 
```
    grid = Grid(Box(0.7, 0.8, 0.9, 1.5, 1.6, 1.7), (3, 3, 3), rand(Float64, (3, 3, 3)),     
        :kJ_mol, [1., 2., 3.])        
```

**Pull request merged**
